### ISSUE TITLE
[Bookmarklets] Shorten Code

### ISSUE THREAD

**Issue by Shluffy** [Scratch-Dev-Team/Scratch-Bookmarklets#4]
To take up less space, however minor that is.
If any of you want to do that, that's fine.

**Comment by ZI-Youtuber** [comment]
@Shluffy nah

**Comment by Shluffy** [comment]
At this point I think that if it is not done here, I'll do it there and then merge it into here I suppose

**Comment by Shluffy** [comment]
I'lll bed doing this unless someone else wants to.

**Comment by Shluffy** [comment]
I am going to start working on this.

**Comment by Shluffy** [comment]
Not done yet.

**Comment by xItzDiamondx** [comment]
Is there a way I can help?

**Comment by Shluffy** [comment]
All shortening done, this will be auto closed when #6 is merged
